"""add board_id to card

Revision ID: d36167a4ff54
Revises: 0ec133e39506
Create Date: 2026-01-02 15:50:57.926365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36167a4ff54'
down_revision = '0ec133e39506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))
        batch_op.drop_column('owener')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('board_id')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owener', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
